name: MLflow Project CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      # Kredensial Docker Hub di Secret and Variable Github
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run MLflow project
        run: |
          python -m mlflow run MLProject --env-manager=local

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          LATEST_RUN_ID=$(python -c "import mlflow; import os; \
            client = mlflow.tracking.MlflowClient('file://' + os.getcwd() + '/mlruns'); \
            runs = client.search_runs(experiment_ids=['0'], order_by=['start_time DESC'], max_results=1); \
            run_id = runs[0].info.run_id; print(run_id)")
          echo "MLFLOW_RUN_ID=$LATEST_RUN_ID" >> $GITHUB_ENV
      
      - name: List Repository Contents After MLflow Run (DEBUG)
        if: always()
        run: |
          echo "Listing all contents of the repository working directory after MLflow run:"
          ls -R .
          echo "--- End of repository listing ---"

      - name: Verify mlruns directory exists (DEBUG)
        if: always()
        run: |
          echo "Checking for mlruns directory in common locations:"
          if [ -d "mlruns" ]; then
            echo "SUCCESS: 'mlruns/' directory found at repository root."
            ls -ld mlruns/
          elif [ -d "MLProject/mlruns" ]; then
            echo "SUCCESS: 'MLProject/mlruns/' directory found."
            ls -ld MLProject/mlruns/
          else
            echo "ERROR: Neither 'mlruns/' nor 'MLProject/mlruns/' directory found after MLflow run. MLflow artifacts might not have been created or are in an unexpected location."
            exit 1
          fi

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build Docker Model
        run: |
          python -m mlflow models build-docker --model-uri "runs:/${{ env.MLFLOW_RUN_ID }}/model" --name attrition-model

      - name: Tag Docker Image
        run: |
          docker tag attrition-model ${{ env.DOCKER_USERNAME }}/attrition-model:latest
      
      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/attrition-model:latest


      - name: Upload MLflow Run Artifacts to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-artifacts-${{ env.MLFLOW_RUN_ID }}
          path: mlruns/${{ env.MLFLOW_RUN_ID }}/artifacts
